:sparkles: commit code is allowed when Lint & UT error for now, will change to denied at this Friday

diff --git a/lib/template/pre-commit b/lib/template/pre-commit
--- a/lib/template/pre-commit
+++ b/lib/template/pre-commit
@@ -111,15 +111,16 @@ if [[ "$STAGED_SERVICE_FILES" != "" ]]; then
     testService
 fi
 
-if [ $PASS == "false" ]
-then
-  failMsg "Git Commit forbidden: Lint & UT check failed, details list as below: "
-  for(( i=0;i<${#ERROR_MSG[@]};i++))
-  do
-    failMsg "${ERROR_MSG[i]}"
-  done
-  exit 1
-else
-  infoMsg "Lint & UT check successful, change commiting..."
-  exit 0
-fi
+# if [ $PASS == "false" ]
+# then
+#   failMsg "Git Commit forbidden: Lint & UT check failed, details list as below: "
+#   for(( i=0;i<${#ERROR_MSG[@]};i++))
+#   do
+#     failMsg "${ERROR_MSG[i]}"
+#   done
+#   exit 1
+# else
+#   infoMsg "Lint & UT check successful, change commiting..."
+#   exit 0
+# fi
+exit 0
